TARGET_ARCH_VARIANT := x86-atom
TARGET_HAS_THIRD_PARTY_APPS := true
BOARD_WPA_SUPPLICANT_DRIVER := AWEXT
BOARD_USES_TSLIB := true
BOARD_USES_I915C := true
BOARD_USES_KBDSENSOR := true

include $(GENERIC_X86_CONFIG_MK)
